### ISSUE TITLE
Fix setup.py and exe_setup.py

### ISSUE THREAD

**Issue by linuxscout** [linuxscout/mishkal#10]
Fix the setup files after the new code organization  
# files
- setup.py file
- exe_setup.py setup file for windows

**Comment by MuhammadAlBarham** [comment]
@linuxscout
What is the help you want here ?

**Comment by linuxscout** [comment]
Salam,
There are many setup files:
* setup_exe to generate exe
* setup.py: generate library

**Comment by linuxscout** [comment]
Salam,
I  try to use PyInstaller, with ".spec" file, 
I add three files:

* mishkal-console.spec
* mishkal-gui.spec
* mishkal-web.spec

I have some problems:
* I want to use only one spec file with multiple exe files within one folder, I did this with pyexe in the past
* I have problems to includes data files from installed packages like :
    *  arramooz-pysqlite
    * maskouk
Thanks
