### ISSUE TITLE
التشكيل خطأ لحرف عندما

### ISSUE THREAD

**Issue by Fahad-Alsaidi** [linuxscout/mishkal#18]
السلام عليكم،
حاليا أستخدم مشكال في تشكيل بعض الكتب، لاحظت أن الحرف "عندما" دائما ما يشكل إلى
عَنْدَمَا 
وهذا خطأ واضح والصحيح 
عِنْدَمَا

**Comment by linuxscout** [comment]
تم الإصلاح

**Comment by Fahad-Alsaidi** [comment]
أخي طه المشكل ما زال قائما ولم تحل، عذرا على التأخير في الرد.
