### ISSUE TITLE
مشكلة التقاء الساكنين

### ISSUE THREAD

**Issue by Fahad-Alsaidi** [linuxscout/mishkal#20]
أثناء استخدامي لمشاكل وأردت أن أشكل هذه العبارة
أصبحت السيدة هدى قلقة
فإن النتيجة تكون
 أَصَبِحَتْ السَّيِّدَةُ هَدَّى قَلِقَةُ
والصحيح
 أَصَبَحْتِ السَّيِّدَةُ هُدَى قَلِقَةُ
حيث يحول سكون التاء إلى كسرة منعا من التقاء الساكنين
سكون التاء وسكون الحرف الأول من التشديد

**Comment by linuxscout** [comment]
عولجت المشكلة، سيحدث الموقع لاحقا
