### ISSUE TITLE
تشكيل كلمة جدا

### ISSUE THREAD

**Issue by Fahad-Alsaidi** [linuxscout/mishkal#21]
في العادة نستخدم جدا صفة بمعنى كثيرا فهي منصوبة دائما ولكن مشكال يظنها فعل مع أن الغالب عليها أنها صفة
بعد بحث في النت وجدت التالي:
إعراب: جِدًّا

جدا : مفعول مطلق لفعل محذوف تقديره : يجد جدا ، كذا في كتاب قواعد اللغة العربية لفؤاد نعمة ص : 70 .
وقيل : جدا: تحتمل وجهين :
الأوّل : صفة لمفعول مطلق محذوف
الثاني : حال بمعنى جادّا
وللعِلم ما يكون صفة لمفعول مطلق قد يصلح إعرابه حالا
وعلى كل حال هي منصوبة

**Comment by linuxscout** [comment]
تم الإصلاح

**Comment by Fahad-Alsaidi** [comment]
المشكلة ما زال قائما
جرب مع هذه الجملة
أحبك جدا جدا يا بحر
