### ISSUE TITLE
Error while installing

### ISSUE THREAD

**Issue by youssefsharief** [linuxscout/mishkal#26]
This is the command I am using: 
`py -2.7 .\bin\mishkal-console.py`

I did not find any module named mysam in the source code

Here is the error:-
 File ".\bin\mishkal-console.py", line 115, in <module>
    import tashkeel.tashkeel as ArabicVocalizer
  File "C:\Code\Repos\Arabic\mishkal\bin\../mishkal\tashkeel\tashkeel.py", line 30, in <module>
    import mysam.tagmaker
ImportError: No module named mysam.tagmaker

**Comment by linuxscout** [comment]
You need mysam package
https://github.com/linuxscout/mysam-tagmanager
or 
https://pypi.org/project/mysam-tagmanager/
