### ISSUE TITLE
Bulk diacretising

### ISSUE THREAD

**Issue by youssefsharief** [linuxscout/mishkal#27]
Are you interested in script file for bulk diacretising. I have finished the script in my fork. If you are interested, I could work on a pull request. Btw the script is inspired from @motazsaad

**Comment by linuxscout** [comment]
Salam,
What do you mean by "bulk diacritization"?

**Comment by youssefsharief** [comment]
W Alaykom El Salam,

A script that outputs a file or several files to another output directory like what is shown here by. This is useful when diacretizing a huge corpus

https://github.com/motazsaad/sphinx-eval/blob/f0479854cc6e2c694828bcda952d749120ed0bc9/get_diacritcs_from_mishkal.sh

**Comment by linuxscout** [comment]
Great, 
I use Mishkal with many shell script to diacritize many file,
I think that your script is usefull, we can add it to tools or bin directory, 
Thanks.

**Comment by youssefsharief** [comment]
Thank you 

I created a new pull request

**Comment by linuxscout** [comment]
great
