### ISSUE TITLE
Mishkal as a plugin for plain text editors

### ISSUE THREAD

**Issue by anasram** [linuxscout/mishkal#29]
I'm wondering why do you try to reinvent the wheel and develop a completely new text editor just to perform tashkeel tasks?

Isn't better if it's developed as a plugin for already exist and popular text editors like Xed, GEdit, Kate, and KWrite?

**Comment by linuxscout** [comment]
You can integrate it also, it's open.
Thaskeel is a library you can use it for under other systems.
