### ISSUE TITLE
Newline is discarded in windows GUI application

### ISSUE THREAD

**Issue by alihabib80** [linuxscout/mishkal#30]
First of all, thanks for this great work.

One issue is that new line '\n' is discarded when clicking Tashkeel. Lines and paragraphs become one paragraph.

It will be more important for large processed text files to fix this.

**Comment by linuxscout** [comment]
السلام عليكم
أعتقد أنني قد حللت هذه المشكلة منذ مدة،
![mishkal-2017-03-19 python konsole_123](https://user-images.githubusercontent.com/450792/51091849-b3c0d780-1790-11e9-8d76-7190f29acec5.png)
هي ليست موجودة في الإصدار المنشور في الملف التنفيذي، لكن في الكود موجودة
يرجى التنبيه إن كانت لا تعمل
