### ISSUE TITLE
Testing Mishkal using command line

### ISSUE THREAD

**Issue by AlaaRoshdy** [linuxscout/mishkal#47]
When I try to run this command to test Mishkal:

> `python3 mishkal/bin/mishkal-console.py -t  "السلام عليكم"`

I get the following error:

> Traceback (most recent call last):
  File "mishkal/bin/mishkal-console.py", line 349, in <module>
    test()
  File "mishkal/bin/mishkal-console.py", line 236, in test
    if compare and filename2 :
UnboundLocalError: local variable 'compare' referenced before assignment

I cannot find an appropriate command that would make me test Mishkal using the command line.

**Comment by linuxscout** [comment]
Salam,
I fixed it, can you confirm?
thanks

**Comment by AlaaRoshdy** [comment]
Thank you. It works now but the sentence gets printed twice. Is there a way to avoid that?

**Comment by linuxscout** [comment]
Thanks for your feedback, I fixed it also.
