### ISSUE TITLE
Problem in tanween 

### ISSUE THREAD

**Issue by zaidalyafeai** [linuxscout/mishkal#49]
Hey, we are added mishkal for speech synthesis https://github.com/ARBML/klaam

```python
from klaam import TextToSpeech

model = TextToSpeech()
model.synthesize("تشرق الشمس صباحا", apply_tshkeel=True)
```

However the generated tashkeel seems to add tanween on `ح` instead of `ا`

```
Raw Text Sequence: تُشْرِقُ الشَّمْسُ صَبَاحًا
```

Is that expected to happen ?

**Comment by linuxscout** [comment]
أهلا أخي زايد،
الصحيح أن يوضع التنوين على الحرف وليس على الألف أي أنه يسبق الألف ولا يتبعه،
لأن الألف لا ينوّن.

هذا الخطأ كثير الانتشار فى الصحف والكتب والمنتديات والرسائل وغيرها ..

(سمعتُ خبراً – رأيتُ شيخاً - وقرأتُ جزءاً)
يجعلون التنوين المفتوح على الألف وهذا خطأ ،
والصواب أن يكون التنوين المفتوح على الحرف الذى قبل الألف هكذا :
(خبرًا - شيخًا - جزءًا)
لأن هذه الألف ليست جزءًا من بنية الكلمة ، وليست الحرف الأخير فيها ، ومن ثَمّ لا تظهر عليها علامات مطلقًا ،
وترى التنوين بالضم والكسر هكذا :
(جاء محمدٌ - سلمتُ على محمدٍ)
ومثلها التنوين بالفتح يُوضع على الحرف وإنما الألف للدلالة على النصب فقط.

**Comment by zaidalyafeai** [comment]
المشكلة أن في تحويل الكتابة إلى صوت يتم اعتبار التنوين قبل الألف 

https://colab.research.google.com/drive/1UWgQjfVc7kMw_vPqnSNXwE8e5259Hpdf?usp=sharing

**Comment by linuxscout** [comment]
الصحيح هو التنوين 

> المشكلة أن في تحويل الكتابة إلى صوت يتم اعتبار التنوين قبل الألف

هذا هو الصحيح ربمان تقصد التنوين بعد الألف، 
إذا كان برنامج يحتسب التنوين بعد الألف، يمكنك إضافة وظيفة تحويل النمط، وهكذا تستعمل نمطا واحدا فقط

**Comment by zaidalyafeai** [comment]
نعم ، شكراً
