### ISSUE TITLE
facing error on installing locally

### ISSUE THREAD

**Issue by donny08** [linuxscout/mishkal#50]
Hi @linuxscout ,
I have cloned the repo on my ubuntu. and following the instruction to run the application 
On running this cmd pip install -r ~/mishkal/requirements.txt

getting error:
Requirement already satisfied: pyarabic>=0.6.2 in /usr/local/lib/python2.7/dist-packages (from -r /root/mishkal/requirements.txt (line 1)) (0.6.10)
Requirement already satisfied: libqutrub>=1.0 in /usr/local/lib/python2.7/dist-packages (from -r /root/mishkal/requirements.txt (line 2)) (1.2.4.1)
Requirement already satisfied: naftawayh>=0.2 in /usr/local/lib/python2.7/dist-packages (from -r /root/mishkal/requirements.txt (line 3)) (0.4)
Requirement already satisfied: tashaphyne>=0.3.1 in /usr/local/lib/python2.7/dist-packages (from -r /root/mishkal/requirements.txt (line 4)) (0.3.4.1)
Requirement already satisfied: arramooz-pysqlite>=0.1 in /usr/local/lib/python2.7/dist-packages (from -r /root/mishkal/requirements.txt (line 5)) (0.3)
Requirement already satisfied: qalsadi>=0.2 in /usr/local/lib/python2.7/dist-packages (from -r /root/mishkal/requirements.txt (line 6)) (0.4.2)
Collecting mysam-tagmanager>=0.3.3 (from -r /root/mishkal/requirements.txt (line 7))
  Could not find a version that satisfies the requirement mysam-tagmanager>=0.3.3 (from -r /root/mishkal/requirements.txt (line 7)) (from versions: 0.1, 0.2, 0.3, 0.3.1)
No matching distribution found for mysam-tagmanager>=0.3.3 (from -r /root/mishkal/requirements.txt (line 7))

**Comment by PAHXO** [comment]
No, you need to compile and install the "mysam-tagmanager 0.3.3" manually from [here](https://github.com/linuxscout/mysam-tagmanager)
You may also want to remove the old version. 

Hopefully they update it in the future to PyPI

**Comment by linuxscout** [comment]
Salam,
I updated mysam-tagmanager on PiPy
regards
