### ISSUE TITLE
'tagMaker' object has no attribute 'encode'

### ISSUE THREAD

**Issue by firas-jolha** [linuxscout/mishkal#54]
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-117-1271c7905abd> in <module>()
      1 import mishkal.tashkeel
      2 vocalizer = mishkal.tashkeel.TashkeelClass()
----> 3 vocalizer.tashkeel(u"غ")

Hello,

I'm using Mishkal for arabic language processing but this error started to occur after every calling of tashkeel function with some arabic words.
In the previous week, It was working fine, now it gives the error below.

/usr/local/lib/python3.7/dist-packages/mishkal/tashkeel.py in tashkeel(self, inputtext, suggestion, format_display)
    437             # Create a special tag
    438             mytagmaker = mysam.tagmaker.tagMaker()
--> 439             mytagmaker.encode(_chosen_list[i].get_tags().split(':'))
    440             mytagmaker.encode(_chosen_list[i].get_type().split(':'))
    441             #~ print(_chosen_list[i].get_tags().split(':'))

AttributeError: 'tagMaker' object has no attribute 'encode'

**Comment by linuxscout** [comment]
Salam,
I updated the library mysam-tagmanager, which make this problem happen,
 I fix this problem, by updating Mishkal library also, the new version is 0.4.1 to fix this bug.
please update mishkal library to have 
thank you for your message
