### ISSUE TITLE
"codernitydb3" dependency is missing in requirements.txt

### ISSUE THREAD

**Issue by naskio** [linuxscout/mishkal#61]
# What did you do?
- I installed mishkal
```
pip install mishkal
```
- Then I run the example code
```python3
import mishkal.tashkeel
vocalizer = mishkal.tashkeel.TashkeelClass()
text = u"تطلع الشمس صباحا"
text = vocalizer.tashkeel(text)
print(text)
```

# What did you expect to happen?
Getting the result ' تَطْلُعُ الشَّمْسُ صَبَاحًا'

# What actually happened?
I got the following exception saying that the module codernitydb3 doesn't exist
```
ModuleNotFoundError: No module named 'codernitydb3'
```

# What are your OS, Python and mishkal versions?
OS: macOS Monterey 12.1
Python: 3.9.7
mishkal: 0.4.1

**Comment by naskio** [comment]
I fixed the issue by installing the package "codernitydb3" manually
```
pip install codernitydb3
```

**Comment by linuxscout** [comment]
Thanks Mehdi
